services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - GPT_API_KEY=${GPT_API_KEY}
      - DEFAULT_USER_ID=${DEFAULT_USER_ID}
      - FRONTEND_URL=${FRONTEND_URL}

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    env_file:
      - web/.env
    environment:
      - VITE_API_URL=http://api:8000