name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_AUDIENCE: authenticated
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
      DEFAULT_USER_ID: test-user-id
      FRONTEND_URL: http://localhost:3000
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Pin to specific version for reproducibility
        version: "0.5.11"
        enable-cache: true
        cache-dependency-glob: "api/uv.lock"
    
    - name: Set up Python
      run: uv python install 3.10
    
    - name: Install dependencies with lockfile
      working-directory: api
      run: uv sync --dev
    
    - name: Lint with flake8
      working-directory: api
      run: |
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      working-directory: api
      run: uv run black --check --diff .
    
    - name: Import sort check with isort
      working-directory: api
      run: uv run isort --check-only --diff .
    
    - name: Type check with mypy
      working-directory: api
      run: uv run mypy . --ignore-missing-imports
    
    - name: Test with pytest
      working-directory: api
      run: uv run pytest tests/ --cov=. --cov-report=xml --cov-report=term-missing
    
    - name: Minimize uv cache
      run: uv cache prune --ci
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./api/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    
    - name: Install dependencies
      run: |
        cd web
        npm ci
    
    - name: Lint
      run: |
        cd web
        npm run lint
    
    - name: Type check
      run: |
        cd web
        npm run type-check
    
    - name: Test
      run: |
        cd web
        npm run test -- --run
    
    - name: Build
      run: |
        cd web
        npm run build